// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZ4Wlg8m42BLSP1G2uFDkKh6mMu4PPJo',
    appId: '1:752569661923:web:c8839e0f8b978f187508d6',
    messagingSenderId: '752569661923',
    projectId: 'esp-32-sending-data',
    authDomain: 'esp-32-sending-data.firebaseapp.com',
    databaseURL: 'https://esp-32-sending-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-32-sending-data.firebasestorage.app',
    measurementId: 'G-W1M1M5S8RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDs_Nz8qFt4H6KAJ3Ro5BNjIrV-1fgu2w',
    appId: '1:752569661923:android:6b43bc53a5e3c0da7508d6',
    messagingSenderId: '752569661923',
    projectId: 'esp-32-sending-data',
    databaseURL: 'https://esp-32-sending-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-32-sending-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXUfW2CD6J5jWdoe98d_VTR99sZERHKtc',
    appId: '1:752569661923:ios:36edf81c38ba08647508d6',
    messagingSenderId: '752569661923',
    projectId: 'esp-32-sending-data',
    databaseURL: 'https://esp-32-sending-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-32-sending-data.firebasestorage.app',
    iosBundleId: 'com.example.smartDrone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXUfW2CD6J5jWdoe98d_VTR99sZERHKtc',
    appId: '1:752569661923:ios:36edf81c38ba08647508d6',
    messagingSenderId: '752569661923',
    projectId: 'esp-32-sending-data',
    databaseURL: 'https://esp-32-sending-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-32-sending-data.firebasestorage.app',
    iosBundleId: 'com.example.smartDrone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZ4Wlg8m42BLSP1G2uFDkKh6mMu4PPJo',
    appId: '1:752569661923:web:cf144a111c0ca2927508d6',
    messagingSenderId: '752569661923',
    projectId: 'esp-32-sending-data',
    authDomain: 'esp-32-sending-data.firebaseapp.com',
    databaseURL: 'https://esp-32-sending-data-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp-32-sending-data.firebasestorage.app',
    measurementId: 'G-T3HV3GKD4R',
  );
}
